apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-gnav
  namespace: rh-ee-tpetkos-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:9524c36a40ee3cb685f4d51b295d75169a9a1c6831d61a99287dff0abee845f1
        name: my-go
        resources: {}
status: {}
